// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpuroapdozyorgkkyisv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwdXJvYXBkb3p5b3Jna2t5aXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDIzNjIsImV4cCI6MjA3MjYxODM2Mn0.AjWkNbbYnczfjCZE5stG-_qrSrnzxbSGFaT_3QPvgpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});